spring:
  config:
    activate:
      on-profile: server1
server:
  port: 9090
  address: 119.70.42.35

server-number: 1

---
spring:
  config:
    activate:
      on-profile: server2

server:
  port: 9091
  address: 119.70.42.35

server-number: 2